# Try it with `helm install --generate-name --dry-run -f helm/afm/values.sample.yaml write-module-chart`
labels:

uuid: "12345678"

# Human readable logs
prettyLogging: false
# zerolog verbosity level
# ref: https://github.com/rs/zerolog#leveled-logging
loggingVerbosity: -1


assets:
- assetID: "test1"
  source:
    connection:
      name: s3
      s3:
        bucket: fybrik-test-bucket
        endpoint: s3.eu-gb.cloud-object-storage.appdomain.cloud
        object_key: test1.parquet
      type: 2
    credentialLocation: htttp://test/test
    format: parquet
  transformations:
  - name: "RedactAction"
    RedactAction:
      columns:
      - col1
      - col2
  - name: "RemoveAction"
    RemoveAction:
      columns:
      - col1
      - col2

